Seems its fixed

diff --git a/positive b/positive
--- a/positive
+++ b/positive
@@ -115,7 +115,7 @@ readonly OPTIONS_LIST="adnf:j:g:o:c:r:s:v"
 ### this breaks calling dcraw and mogrify. Better let this commented-out.
 readonly DEFAULT_IFS="${IFS}"
 readonly SAFER_IFS=$'\n\t'
-#IFS="${SAFER_IFS}"
+IFS="${SAFER_IFS}"
 
 
 # Filesystem basics
@@ -378,7 +378,10 @@ function applyMogrify {
     # ---------------------------------------
 
     e_verbous "$(printf "\nmogrify %s " "${mogrify_options}")"
+
+    IFS="${DEFAULT_IFS}"
     mogrify ${mogrify_options} "${output_tiff}"
+    IFS="${SAFER_IFS}"
 }
 
 
@@ -434,19 +437,18 @@ function processNegatives {
     require awk
 
 
-
-    #IFS=$''
-    # Files to work on.
-    local -r INPUT_FILES=("${@}")
-
-    # for INPUT_TIFF in ${INPUT_FILES[@]}; do
-    # #for INPUT_TIFF in "${@}"; do
-    #   printf "processNegatives: %s \n" $INPUT_TIFF
-    # done
-    # #IFS="${DEFAULT_IFS}"
-    # exit;
+    local -r INPUT_TIFF="${1}"
+    e_info "$(printf "\n%s\n" "${INPUT_TIFF}")"
 
 
+    # ---------------------------------------
+    # Plausibility check
+    # ---------------------------------------
+    if [ ! -f "${INPUT_TIFF}" ]; then
+        e_warning "$(printf 'processNegatives: %s is not a regular file.' "${INPUT_TIFF}")"
+        # continue;
+        exit 1
+    fi
 
 
 
@@ -596,67 +598,57 @@ function processNegatives {
 
 
     # =============================================================
-    #  The Loop: Process each file given
+    #  Process the file given
     # =============================================================
-    for INPUT_TIFF in "${INPUT_FILES[@]}"
-    do
-        printf "DEBUG:  %s\n" "${INPUT_TIFF}"
+
+
+    # ---------------------------------------
+    # Filename magic
+    # ---------------------------------------
+    local input_file_extension="${INPUT_TIFF##*.}";
+    local input_file_basename="${INPUT_TIFF%.$input_file_extension}"
+    input_file_basename="${input_file_basename##*/}" # remove trailing slash
+
+    local output_tiff="${output_directory}/${input_file_basename}${RESULT_SUFFIX}.${input_file_extension}"
+    local output_jpeg="${output_directory}/${input_file_basename}${RESULT_SUFFIX}.jpg"
+
+
+
+    # ---------------------------------------
+    #  Do 'real' inversion and image editing
+    # ---------------------------------------
+    e_verbous "$(echo;)"
+    printf "Create positive image: "
+    (applyMogrify "${INPUT_TIFF}" "${mogrify_options}" "${output_tiff}" "${output_jpeg}") || {
+        e_warning "$(printf "Could not create positive: %s" "${INPUT_TIFF}")"
         # continue
+        exit 1
+    }
+    e_success ""
 
 
-        # ---------------------------------------
-        # Plausibility check
-        # ---------------------------------------
-        if [ ! -f "${INPUT_TIFF}" ]; then
-            e_warning "$(printf 'processNegatives: %s is not a regular file.' "${INPUT_TIFF}")"
-            continue;
-        fi
+    # ---------------------------------------
+    # Do nothing else if JPEG conversion not required
+    # ---------------------------------------
+    if [ $jpeg_quality -eq 0 ]; then
+        e_result "$(printf "Result: %s" "${output_tiff}")"
+        # continue
+        exit 0
+    fi
 
-        # ---------------------------------------
-        # Filename magic
-        # ---------------------------------------
-        local input_file_extension="${INPUT_TIFF##*.}";
-        local input_file_basename="${INPUT_TIFF%.$input_file_extension}"
-        input_file_basename="${input_file_basename##*/}" # remove trailing slash
-
-        local output_tiff="${output_directory}/${input_file_basename}${RESULT_SUFFIX}.${input_file_extension}"
-        local output_jpeg="${output_directory}/${input_file_basename}${RESULT_SUFFIX}.jpg"
-
-        e_info "$(printf "\n%s\n" "${INPUT_TIFF}")"
-
-        # ---------------------------------------
-        #  Do 'real' inversion and image editing
-        # ---------------------------------------
-        e_verbous "$(echo;)"
-        printf "Create positive image: "
-        (applyMogrify "${INPUT_TIFF}" "${mogrify_options}" "${output_tiff}" "${output_jpeg}") || {
-            e_warning "$(printf "Could not create positive: %s" "${INPUT_TIFF}")"
-            continue
-        }
+    # So JPEG conversion is required:
+    printf "Convert to JPG: "
+    (convertToJpeg "${output_tiff}" "${convert_options}" "${output_jpeg}") \
+    && {
         e_success ""
-
-
-        # ---------------------------------------
-        # Do nothing else if JPEG conversion not required
-        # ---------------------------------------
-        if [ $jpeg_quality -eq 0 ]; then
-            e_result "$(printf "Result: %s" "${output_tiff}")"
-            continue
+        rm "${output_tiff}" || e_warning "$(printf 'Can not remove file %s' "${output_tiff}")"
+        e_result "$(printf "Result: %s" "${output_jpeg}")"
+    } || {
+        if [ -f "${output_tiff}" ]; then
+            e_warning "$(printf "Did not convert to JPEG, result still:\n%s" "${output_tiff}")"
         fi
+    }
 
-        # So JPEG conversion is required:
-        printf "Convert to JPG: "
-        (convertToJpeg "${output_tiff}" "${convert_options}" "${output_jpeg}") \
-        && {
-            e_success ""
-            rm "${output_tiff}" || e_warning "$(printf 'Can not remove file %s' "${output_tiff}")"
-            e_result "$(printf "Result: %s" "${output_jpeg}")"
-        } || {
-            if [ -f "${output_tiff}" ]; then
-                e_warning "$(printf "Did not convert to JPEG, result still:\n%s" "${output_tiff}")"
-            fi
-        }
-    done
 }
 
 
@@ -673,8 +665,6 @@ function main {
         printf "Run '%s --help' or with '-h' to get a list of all options.\n" "${SCRIPT_NAME}"
         exit 1
     fi
-
-
 
 
     # ---------------------------------------
@@ -837,7 +827,7 @@ function main {
                 # "Anything else must be an image parameter"
                 # This is a WORKAROUND, as without this "*)" block any given image parameters
                 # after the arguments seem to get lost (i.e., stuck in last $__option checked).
-                image_parameters+=${__option}
+                image_parameters+=" ${__option}"
                 image_parameters_array+=(${__option})
                 ;;
         esac
@@ -859,18 +849,11 @@ function main {
         runBatchMode ${recursion_arguments}
     else
 
-        # This IFS line makes sure that processNegatives can handle parameters correctly
-        #IFS="${SAFER_IFS}"
-
-        # DEBUG: This will not work
-        for INPUT_TIFF in "${image_parameters_array[*]}"; do
-            printf "\nmain:%s\n" "${INPUT_TIFF}";
+        for INPUT_TIFF in "${image_parameters_array[@]}"; do
+            (processNegatives "${INPUT_TIFF}")
         done
-        exit;
-        processNegatives ${image_parameters}
 
-        # Reset IFS
-        #IFS="${DEFAULT_IFS}"
+
     fi;
 
 
@@ -878,4 +861,4 @@ function main {
 
 }
 
-main ${@}
+main "${@}"
